general.import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/themes/themes/everforest_dark.toml"
  # "~/.config/alacritty/themes/themes/afterglow.toml"
]

[window]
dynamic_padding = true
opacity = 0.8
# opacity = 1.0

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[colors.cursor]
text = "#4d4d4c"

[colors.vi_mode_cursor]
text = "#4d4d4c"

[selection]
save_to_clipboard = true

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[scrolling]
history = 10000
multiplier = 5 # Number of lines scrolled for each input scroll increment

