general.import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/custom_themes/everforest",
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.85
# opacity = 1.0

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
# unfocused_hollow = true

[colors.cursor]
text = "#4d4d4c"
# cursor = "#4d4d4c"

[selection]
save_to_clipboard = true

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "auto"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

