general.import = [
  "~/.config/alacritty/keybindings.toml",
  # THEMES 
  "~/.config/alacritty/themes/themes/everforest_dark.toml"
  # "~/.config/alacritty/themes/themes/afterglow.toml"
  # catppuccin theme
  # "~/.config/alacritty/themes/themes/catppuccin.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
dynamic_padding = true
opacity = 0.5
# opacity = 1.0 

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

# [colors.cursor]
# text = "#4d4d4c"
# text = "#d3c6aa"

# [colors.vi_mode_cursor]
# text = "#4d4d4c"

[selection]
save_to_clipboard = true

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

# [colors.selection]
# text = "CellForeground"
# background = "#44475a"

[scrolling]
history = 10000
multiplier = 5 # Number of lines scrolled for each input scroll increment

