[colors.primary]
foreground = "#eaeaea"
background = "#2c323b"

[colors.cursor]
text = "#2c323b"
cursor = "#eaeaea"

[colors.selection]
text = "#2c323b"
background = "#eaeaea"

[colors.normal]
black = "#242a32"
red = "#d54e53"
green = "#98c379"
yellow = "#e5c07b"
blue = "#83a598"
magenta = "#c678dd"
cyan = "#70c0ba"
white = "#eaeaea"

[colors.bright]
black = "#666666"
red = "#ec3e45"
green = "#90c966"
yellow = "#edbf69"
blue = "#73ba9f"
magenta = "#c858e9"
cyan = "#2bcec2"
white = "#ffffff"
